name: Fetch latest data

on:
  push:
  repository_dispatch:
  schedule:
    - cron:  '25 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - uses: actions/cache@v1
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt
    - name: Fetch latest data
      run: |-
        conditional-get -v https://health-infobase.canada.ca/src/data/covidLive/covid19.csv -o covid19__latest.csv 
        conditional-get -v https://health-infobase.canada.ca/src/data/covidLive/covid19-epiSummary-casesovertime.csv -o covid19-epiSummary-casesovertime__latest.csv 
        conditional-get -v https://health-infobase.canada.ca/src/data/covidLive/covid19-epiSummary-agegroups2.csv -o covid19-epiSummary-agegroups2__latest.csv 
        conditional-get -v https://health-infobase.canada.ca/src/data/covidLive/covid19-epiSummary-probableexposure.csv -o covid19-epiSummary-probableexposure__latest.csv
        conditional-get -v https://health-infobase.canada.ca/src/data/covidLive/covid19-epiSummary-symptoms.csv -o covid19-epiSummary-symptoms__latest.csv 
        conditional-get -v https://health-infobase.canada.ca/src/data/covidLive/covid19-epiSummary-severity.csv -o covid19-epiSummary-severity__latest.csv 
        conditional-get -v http://www.bccdc.ca/Health-Info-Site/Documents/BCCDC_COVID19_Dashboard_Case_Details.csv -o BC__BCCDC_COVID19_Dashboard_Case_Details__latest.csv 
        conditional-get -v http://www.bccdc.ca/Health-Info-Site/Documents/BCCDC_COVID19_Dashboard_Lab_Information.csv -o BC__BCCDC_COVID19_Dashboard_Lab_Information__latest.csv
        conditional-get -v https://data.ontario.ca/dataset/f4f86e54-872d-43f8-8a86-3892fd3cb5e6/resource/ed270bb8-340b-41f9-a7c6-e8ef587e6d11/download/covidtesting.csv -o ON__covidtesting__latest.csv 
        conditional-get -v https://data.ontario.ca/dataset/f4112442-bdc8-45d2-be3c-12efae72fb27/resource/455fd63b-603d-4608-8216-7d8647f43350/download/conposcovidloc.csv -o ON__conposcovidloc__latest.csv
        conditional-get -v https://services.arcgis.com/mMUesHYPkXjaFGfS/ArcGIS/rest/services/mb_covid_cases_by_status_daily/FeatureServer/0/query?where=ObjectId+%3E+0&objectIds=&time=&resultType=none&outFields=*&returnIdsOnly=false&returnUniqueIdsOnly=false&returnCountOnly=false&returnDistinctValues=false&cacheHint=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&having=&resultOffset=&resultRecordCount=&sqlFormat=none&f=pjson&token= -o MB__mb_covid_cases_by_status_daily__latest.json
        conditional-get -v https://services.arcgis.com/mMUesHYPkXjaFGfS/ArcGIS/rest/services/mb_covid_cases_summary_info/FeatureServer/0/query?where=ObjectID%3E0&objectIds=&time=&resultType=none&outFields=*&returnIdsOnly=false&returnUniqueIdsOnly=false&returnCountOnly=false&returnDistinctValues=false&cacheHint=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&having=&resultOffset=&resultRecordCount=&sqlFormat=none&f=pjson&token= -o MB__mb_covid_cases_summary_info__latest.json
        conditional-get -v https://services.arcgis.com/mMUesHYPkXjaFGfS/ArcGIS/rest/services/mb_covid_cases_by_demographics_rha/FeatureServer/0/query?where=ObjectID%3E0&objectIds=&time=&resultType=none&outFields=*&returnIdsOnly=false&returnUniqueIdsOnly=false&returnCountOnly=false&returnDistinctValues=false&cacheHint=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&having=&resultOffset=&resultRecordCount=&sqlFormat=none&f=pjson&token= -o MB__mb_covid_cases_by_demographics_rha__latest.json
        conditional-get -v https://services.arcgis.com/mMUesHYPkXjaFGfS/ArcGIS/rest/services/Manitoba_COVID19_RHA_Totals/FeatureServer/0/query?where=ObjectId%3E0&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&resultType=none&distance=0.0&units=esriSRUnit_Meter&returnGeodetic=false&outFields=RHACODE%2C+RHAName%2C+Lab_Confirmed%2C+Probable%2C+Total_Cases&returnGeometry=false&returnCentroid=false&featureEncoding=esriDefault&multipatchOption=xyFootprint&maxAllowableOffset=&geometryPrecision=&outSR=&datumTransformation=&applyVCSProjection=false&returnIdsOnly=false&returnUniqueIdsOnly=false&returnCountOnly=false&returnExtentOnly=false&returnQueryGeometry=false&returnDistinctValues=false&cacheHint=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&having=&resultOffset=&resultRecordCount=&returnZ=false&returnM=false&returnExceededLimitFeatures=true&quantizationParameters=&sqlFormat=none&f=pjson&token= -o MB__Manitoba_COVID19_RHA_Totals__latest.json
    - name: Fetch table 13-10-0766-01
      run: |-
        conditional-get -v https://www150.statcan.gc.ca/n1/tbl/csv/13100766-eng.zip
        unzip 13100766-eng.zip
        mv 13100766.csv 13100766__latest.csv
        mv 13100766_MetaData.csv 13100766_MetaData.csv__latest.csv
        rm 13100766-eng.zip
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
